name: ReleaseOnline
version: 1.0
author: CashMan3000
main: xyz.cm3k.ReleaseOnline.plugin.ReleaseOnlinePlugin
description: Basic commands from ReleaseOnline
website: https://www.cm3k.xyz/

commands:
  rules:
    description: Displays the server rules.
    #usage: /<command>
  rohelp:
    description: Displays server help.
    #usage: /<command> <args>
    claims:
      description: Displays claiming help information.